// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abhpwnfajkjxoyudvfwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiaHB3bmZhamtqeG95dWR2ZndwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NDY2NDksImV4cCI6MjA3MjQyMjY0OX0.K_mG61o1LbiR9pKhmZoMPQBziErLh5yuspIsQA4oXMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});